sonar.projectKey=dgm17076_PROYECTO
sonar.projectName=Gestor de Donaciones
sonar.organization=dgm17076
sonar.sources=src,public
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=coverage/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
