sonar.projectKey=gestor-donaciones-v2
sonar.projectName=Gestor de Donaciones V2
sonar.sources=src,public
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=coverage/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
