const {createServer}=require('../src/app');
const store=require('../src/store');
const jwt=require('../src/jwt');
let server,base;
beforeEach(done=>{store.reset();server=createServer();server.listen(0,()=>{base=`http://127.0.0.1:${server.address().port}`;done()})});
afterEach(done=>{server.close(()=>done())});
async function req(path,method='GET',data,token){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:data!==undefined&&data!==null?JSON.stringify(data):undefined});let response;try{response=await r.json()}catch{response=null}return {status:r.status,body:response}}
async function user(){await req('/api/auth/register','POST',{name:'Ana García',email:'ana@test.mx',password:'12345678'});return (await req('/api/auth/login','POST',{email:'ana@test.mx',password:'12345678'})).body}
async function admin(){return (await req('/api/auth/login','POST',{email:'admin@donaciones.mx',password:'Donaciones123'})).body}
test('health',async()=>expect((await req('/api/health')).status).toBe(200));
test('registro válido',async()=>expect((await req('/api/auth/register','POST',{name:'Ana',email:'ana@test.mx',password:'12345678'})).status).toBe(201));
test('rechaza registro inválido',async()=>expect((await req('/api/auth/register','POST',{name:'',email:'x',password:'1'})).status).toBe(400));
test('rechaza correo duplicado',async()=>{await req('/api/auth/register','POST',{name:'Ana',email:'ana@test.mx',password:'12345678'});expect((await req('/api/auth/register','POST',{name:'Otra',email:'ANA@test.mx',password:'12345678'})).status).toBe(409)});
test('login inválido',async()=>expect((await req('/api/auth/login','POST',{email:'nadie@test.mx',password:'incorrecta'})).status).toBe(401));
test('lista centros',async()=>{const r=await req('/api/centros');expect(r.status).toBe(200);expect(r.body.centers.length).toBeGreaterThan(0)});
test('requiere JWT',async()=>expect((await req('/api/donaciones')).status).toBe(401));
test('rechaza JWT inválido',async()=>expect((await req('/api/donaciones','GET',null,'abc.def.ghi')).status).toBe(401));
test('crea y lista donación con trazabilidad',async()=>{let u=await user();let d=await req('/api/donaciones','POST',{type:'Alimentos',description:'Arroz',quantity:10,centerId:'c1'},u.token);expect(d.status).toBe(201);expect(d.body.donation.donorName).toBe('Ana García');expect(d.body.donation.createdAt).toBeTruthy();expect(d.body.donation.centerName).toBe('Centro Norte');expect(d.body.donation.id).toMatch(/^DON-/);let l=await req('/api/donaciones','GET',null,u.token);expect(l.status).toBe(200);expect(l.body.donations).toHaveLength(1)});
test('rechaza donación inválida',async()=>{let u=await user();expect((await req('/api/donaciones','POST',{type:'',quantity:0,centerId:'no'},u.token)).status).toBe(400)});
test('propietario cancela registrada',async()=>{let u=await user();let d=await req('/api/donaciones','POST',{type:'Ropa',quantity:3,centerId:'c2'},u.token);let c=await req(`/api/donaciones/${d.body.donation.id}/cancelar`,'PATCH',{},u.token);expect(c.status).toBe(200);expect(c.body.donation.status).toBe('Cancelada');expect((await req(`/api/donaciones/${d.body.donation.id}/cancelar`,'PATCH',{},u.token)).status).toBe(409)});
test('cancelar inexistente devuelve 404',async()=>{let u=await user();expect((await req('/api/donaciones/DON-NO/cancelar','PATCH',{},u.token)).status).toBe(404)});
test('otro usuario no puede cancelar donación ajena',async()=>{let u=await user();let d=await req('/api/donaciones','POST',{type:'Ropa',quantity:1,centerId:'c1'},u.token);await req('/api/auth/register','POST',{name:'Luis',email:'luis@test.mx',password:'12345678'});let l=(await req('/api/auth/login','POST',{email:'luis@test.mx',password:'12345678'})).body;expect((await req(`/api/donaciones/${d.body.donation.id}/cancelar`,'PATCH',{},l.token)).status).toBe(403)});
test('usuario no accede a reporte admin',async()=>{let u=await user();expect((await req('/api/reportes/resumen','GET',null,u.token)).status).toBe(403)});
test('usuario no cambia estado',async()=>{let u=await user();let d=await req('/api/donaciones','POST',{type:'Ropa',quantity:1,centerId:'c1'},u.token);expect((await req(`/api/donaciones/${d.body.donation.id}/estado`,'PATCH',{status:'Recibida'},u.token)).status).toBe(403)});
test('admin cambia estados y obtiene reporte',async()=>{let u=await user();let d=await req('/api/donaciones','POST',{type:'Alimentos',quantity:2,centerId:'c1'},u.token);let a=await admin();expect((await req(`/api/donaciones/${d.body.donation.id}/estado`,'PATCH',{status:'Recibida'},a.token)).status).toBe(200);expect((await req(`/api/donaciones/${d.body.donation.id}/estado`,'PATCH',{status:'Entregada'},a.token)).status).toBe(200);let r=await req('/api/reportes/resumen','GET',null,a.token);expect(r.status).toBe(200);expect(r.body.delivered).toBe(1)});
test('admin rechaza estado inválido e id inexistente',async()=>{let a=await admin();expect((await req('/api/donaciones/no/estado','PATCH',{status:'Recibida'},a.token)).status).toBe(404);let u=await user();let d=await req('/api/donaciones','POST',{type:'Ropa',quantity:1,centerId:'c1'},u.token);expect((await req(`/api/donaciones/${d.body.donation.id}/estado`,'PATCH',{status:'Otro'},a.token)).status).toBe(400)});
test('donación cancelada no puede avanzar',async()=>{let u=await user();let d=await req('/api/donaciones','POST',{type:'Ropa',quantity:1,centerId:'c1'},u.token);await req(`/api/donaciones/${d.body.donation.id}/cancelar`,'PATCH',{},u.token);let a=await admin();expect((await req(`/api/donaciones/${d.body.donation.id}/estado`,'PATCH',{status:'Recibida'},a.token)).status).toBe(409)});
test('404 para ruta desconocida',async()=>expect((await req('/api/no-existe')).status).toBe(404));
test('JWT expirado se rechaza',async()=>{const t=jwt.sign({sub:'u-admin',role:'admin'},'clave-academica-donaciones-2026',-1);expect((await req('/api/donaciones','GET',null,t)).status).toBe(401)});
