const http=require('http'),fs=require('fs'),path=require('path'); const {URL}=require('url'); const S=require('./store'),J=require('./jwt'); const SECRET=process.env.JWT_SECRET||'clave-academica-donaciones-2026';
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});res.end(body)}
function body(req){return new Promise((ok,bad)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){bad(e)}})})} function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error('NO_AUTH');return J.verify(h.slice(7),SECRET)} function safe(u){return{id:u.id,name:u.name,email:u.email,role:u.role}} function enrich(d){const u=S.users.find(x=>x.id===d.userId),c=S.centers.find(x=>x.id===d.centerId);return{...d,donorName:u?.name||'Usuario',donorEmail:u?.email||'',centerName:c?.name||d.centerId}}
function createServer(){return http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');
if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true});
if(req.method==='POST'&&url.pathname==='/api/auth/register'){const x=await body(req),name=String(x.name||'').trim(),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||'');if(!name||!email.includes('@')||password.length<8)return json(res,400,{error:'Completa correctamente todos los datos'});if(S.users.some(u=>u.email===email))return json(res,409,{error:'El correo ya está registrado'});const u={id:`u${Date.now()}`,name,email,password:S.hashPassword(password),role:'usuario'};S.users.push(u);return json(res,201,{user:safe(u)})}
if(req.method==='POST'&&url.pathname==='/api/auth/login'){const x=await body(req),u=S.users.find(z=>z.email===String(x.email||'').trim().toLowerCase());if(!u||!S.verifyPassword(String(x.password||''),u.password))return json(res,401,{error:'Correo o contraseña incorrectos'});return json(res,200,{token:J.sign({sub:u.id,role:u.role,email:u.email},SECRET),user:safe(u)})}
if(req.method==='GET'&&url.pathname==='/api/centros')return json(res,200,{centers:S.centers});
if(req.method==='GET'&&url.pathname==='/api/donaciones'){const p=auth(req),list=p.role==='admin'?S.donations:S.donations.filter(d=>d.userId===p.sub);return json(res,200,{donations:list.map(enrich)})}
if(req.method==='POST'&&url.pathname==='/api/donaciones'){const p=auth(req),x=await body(req),type=String(x.type||'').trim(),description=String(x.description||'').trim(),quantity=Number(x.quantity),centerId=String(x.centerId||'');if(!type||quantity<=0||!S.centers.some(c=>c.id===centerId))return json(res,400,{error:'Completa correctamente la donación'});const now=new Date().toISOString(),d={id:`DON-${Date.now().toString().slice(-7)}`,userId:p.sub,type,description,quantity,centerId,status:'Registrada',createdAt:now,updatedAt:now,cancelledAt:null};S.donations.push(d);return json(res,201,{donation:enrich(d)})}
let m=url.pathname.match(/^\/api\/donaciones\/([^/]+)\/cancelar$/);if(req.method==='PATCH'&&m){const p=auth(req),d=S.donations.find(x=>x.id===m[1]);if(!d)return json(res,404,{error:'Donación no encontrada'});if(p.role!=='admin'&&d.userId!==p.sub)return json(res,403,{error:'No puedes cancelar esta donación'});if(d.status!=='Registrada')return json(res,409,{error:'Solo se puede cancelar una donación Registrada'});d.status='Cancelada';d.cancelledAt=d.updatedAt=new Date().toISOString();return json(res,200,{donation:enrich(d)})}
m=url.pathname.match(/^\/api\/donaciones\/([^/]+)\/estado$/);if(req.method==='PATCH'&&m){const p=auth(req);if(p.role!=='admin')return json(res,403,{error:'Solo administrador'});const x=await body(req),d=S.donations.find(z=>z.id===m[1]);if(!d)return json(res,404,{error:'Donación no encontrada'});if(d.status==='Cancelada')return json(res,409,{error:'Una donación cancelada ya no puede avanzar'});if(!['Registrada','Recibida','Entregada'].includes(x.status))return json(res,400,{error:'Estado inválido'});d.status=x.status;d.updatedAt=new Date().toISOString();return json(res,200,{donation:enrich(d)})}
if(req.method==='GET'&&url.pathname==='/api/reportes/resumen'){const p=auth(req);if(p.role!=='admin')return json(res,403,{error:'Solo administrador'});const n=s=>S.donations.filter(d=>d.status===s).length;return json(res,200,{total:S.donations.length,registered:n('Registrada'),received:n('Recibida'),delivered:n('Entregada'),cancelled:n('Cancelada'),users:S.users.length})}
if(req.method==='GET'){let f=url.pathname==='/'?'index.html':url.pathname.slice(1);if(/^[\w.-]+$/.test(f)){const fp=path.join(__dirname,'..','public',f);if(fs.existsSync(fp)){res.writeHead(200,{'Content-Type':{'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript'}[path.extname(fp)]||'text/plain'});return fs.createReadStream(fp).pipe(res)}}} return json(res,404,{error:'No encontrado'});
}catch(e){if(['NO_AUTH','TOKEN_INVALIDO','TOKEN_EXPIRADO'].includes(e.message))return json(res,401,{error:'Inicia sesión nuevamente'});return json(res,400,{error:'Solicitud inválida'})}})} module.exports={createServer};